---
- name: check uptime of a server
  hosts: 
    - lab1
    - lab2
    - loclahost

  tasks:
    - name: check the uptime of server
      command: uptime
      register: out
    
    - name: Print the results
      debug:
        msg: " {{ out.stdout_lines }} "
